namespace InventoryBot.Application.Services;

public class LocalizationService
{
    private static readonly Dictionary<string, Dictionary<string, string>> _resources = new()
    {
        ["uz"] = new()
        {
            ["Welcome"] = "Xush kelibsiz! Iltimos, tilni tanlang:",
            ["LanguageSelected"] = "Til tanlandi: O'zbekcha",
            ["WaitAdmin"] = "Admin sizga rol berishini kuting.",
            ["WelcomeBack"] = "Xush kelibsiz, {0}. Panel uchun /admin deb yozing.",
            ["PasswordSet"] = "Parol o'rnatildi. Siz endi Asosiy Adminsiz. Kirish uchun /admin deb yozing.",
            ["EnterPassword"] = "Tizim ishga tushmagan. Yangi Admin parolini kiriting:",
            ["EnterExistingPassword"] = "Sizda Admin Panelga kirish huquqing yo'q. Admin parolini kiriting:",
            ["AccessDenied"] = "Sizda Admin Panelga kirish huquqi yo'q.",
            ["NoPending"] = "Tasdiqlashni kutayotganlar yo'q.",
            ["SelectUser"] = "Foydalanuvchini tanlang:",
            ["SelectRole"] = "Foydalanuvchi ID {0} uchun rol tanlang:",
            ["RoleUpdated"] = "Foydalanuvchi roli {0} ga o'zgardi.",
            ["YourRoleUpdated"] = "Sizning rolingiz o'zgardi: {0}",
            ["ChangePass"] = "Yangi parolni kiriting:",
            ["PassChanged"] = "Parol muvaffaqiyatli o'zgartirildi.",
            ["Action_Deputy"] = "O'rinbosar qilish",
            ["Action_Storekeeper"] = "Omborchi qilish",
            ["Action_Admin"] = "Admin qilish",
            ["Btn_Notifications"] = "Kutayotganlar ({0})",
            ["Btn_ChangePass"] = "Parolni o'zgartirish",
            ["Btn_AddWarehouse"] = "Ombor qo'shish",
            ["Btn_WarehouseList"] = "Omborlar ro'yxati",
            ["Btn_AddCustomer"] = "Xaridor qo'shish",
            ["Btn_CustomerList"] = "Xaridorlar ro'yxati",
            ["EnterWarehouseName"] = "Ombor nomini kiriting:",
            ["WarehouseAdded"] = "Ombor muvaffaqiyatli qo'shildi: {0}",
            ["WarehouseDuplicate"] = "❌ Bu nomdagi ombor allaqachon mavjud: {0}",
            ["WarehouseListTitle"] = "📦 Omborlar ro'yxati:",
            ["EnterCustomerName"] = "Xaridor nomini kiriting:",
            ["CustomerAdded"] = "Xaridor muvaffaqiyatli qo'shildi: {0}",
            ["CustomerDuplicate"] = "❌ Bu nomdagi xaridor allaqachon mavjud: {0}",
            ["CustomerListTitle"] = "👥 Xaridorlar ro'yxati:",
            ["SelectWarehouse"] = "Foydalanuvchini qaysi omborga biriktirasiz?",
            ["UserAssignedToWarehouse"] = "Foydalanuvchi {0} omboriga biriktirildi.",
            ["NoWarehouses"] = "Hozircha omborlar yo'q. Avval ombor qo'shing.",
            ["NoCustomers"] = "Hozircha xaridorlar yo'q. Avval xaridor qo'shing.",
            ["Menu_Warehouses"] = "📦 Omborlar",
            ["Menu_Customers"] = "👥 Xaridorlar",
            ["Btn_Add"] = "Qo'shish",
            ["Btn_List"] = "Ro'yxat",
            ["Btn_Back"] = "🔙 Ortga",
            ["Title_ManageWarehouses"] = "Omborlar boshqaruvi:",
            ["Title_ManageCustomers"] = "Xaridorlar boshqaruvi:",
            ["EnterOldPassword"] = "🔒 Iltimos, avval eski parolni kiriting:",
            ["OldPasswordIncorrect"] = "❌ Eski parol noto'g'ri!",
            ["NewPasswordSameAsOld"] = "❌ Yangi parol eski parol bilan bir xil bo'lishi mumkin emas!",
            ["NewPasswordSameAsOld"] = "❌ Yangi parol eski parol bilan bir xil bo'lishi mumkin emas!",
            ["Btn_Close"] = "❌ Yopish",
            // Storekeeper
            ["WarehouseTitle"] = "🏠 Ombor: {0}",
            ["Btn_AddProduct"] = "➕ Mahsulot qo'shish",
            ["EnterProductName"] = "📝 Mahsulot nomini kiriting:",
            ["SelectUnit"] = "⚖️ O'lchov birligini tanlang:",
            ["Unit_Kg"] = "Kg",
            ["Unit_Ton"] = "Tonna",
            ["Unit_Meter"] = "Metr",
            ["Unit_Piece"] = "Dona",
            ["Unit_Liter"] = "Litr",
            ["ProductSaved"] = "✅ Mahsulot saqlandi: {0} ({1})",
            ["NotStorekeeper"] = "⛔️ Siz omborchi emassiz.",
            ["NoWarehouseAssigned"] = "⛔️ Sizga ombor biriktirilmagan."
        },
        ["ru"] = new()
        {
            ["Welcome"] = "Добро пожаловать! Пожалуйста, выберите язык:",
            ["LanguageSelected"] = "Язык выбран: Русский",
            ["WaitAdmin"] = "Подождите, пока администратор назначит вам роль.",
            ["WelcomeBack"] = "С возвращением, {0}. Введите /admin для входа в панель.",
            ["PasswordSet"] = "Пароль установлен. Вы теперь Главный Администратор. Введите /admin для доступа.",
            ["EnterPassword"] = "Система не инициализирована. Введите новый пароль администратора:",
            ["AccessDenied"] = "У вас нет доступа к Панели Администратора.",
            ["NoPending"] = "Нет пользователей, ожидающих подтверждения.",
            ["SelectUser"] = "Выберите пользователя:",
            ["SelectRole"] = "Выберите роль для пользователя ID {0}:",
            ["RoleUpdated"] = "Роль пользователя обновлена на {0}.",
            ["YourRoleUpdated"] = "Ваша роль обновлена: {0}",
            ["ChangePass"] = "Введите новый пароль:",
            ["PassChanged"] = "Пароль успешно изменен.",
            ["Action_Deputy"] = "Сделать заместителем",
            ["Action_Storekeeper"] = "Сделать кладовщиком",
            ["Action_Admin"] = "Сделать админом",
            ["Btn_Notifications"] = "Ожидающие ({0})",
            ["Btn_ChangePass"] = "Изменить пароль",
            ["Btn_AddWarehouse"] = "Добавить склад",
            ["Btn_WarehouseList"] = "Список складов",
            ["Btn_AddCustomer"] = "Добавить клиента",
            ["Btn_CustomerList"] = "Список клиентов",
            ["EnterWarehouseName"] = "Введите название склада:",
            ["WarehouseAdded"] = "Склад успешно добавлен: {0}",
            ["WarehouseDuplicate"] = "❌ Склад с таким названием уже существует: {0}",
            ["WarehouseListTitle"] = "📦 Список складов:",
            ["EnterCustomerName"] = "Введите имя клиента:",
            ["CustomerAdded"] = "Клиент успешно добавлен: {0}",
            ["CustomerDuplicate"] = "❌ Клиент с таким именем уже существует: {0}",
            ["CustomerListTitle"] = "👥 Список клиентов:",
            ["SelectWarehouse"] = "К какому складу прикрепить пользователя?",
            ["UserAssignedToWarehouse"] = "Пользователь прикреплен к складу {0}.",
            ["NoWarehouses"] = "Складов пока нет. Сначала добавьте склад.",
            ["NoCustomers"] = "Клиентов пока нет. Сначала добавьте клиента.",
            ["Menu_Warehouses"] = "📦 Склады",
            ["Menu_Customers"] = "👥 Клиенты",
            ["Btn_Add"] = "Добавить",
            ["Btn_List"] = "Список",
            ["Btn_Back"] = "🔙 Назад",
            ["Title_ManageWarehouses"] = "Управление складами:",
            ["Title_ManageCustomers"] = "Управление клиентами:",
            ["EnterOldPassword"] = "🔒 Пожалуйста, введите старый пароль:",
            ["OldPasswordIncorrect"] = "❌ Старый пароль неверен!",
            ["NewPasswordSameAsOld"] = "❌ Новый пароль не может совпадать со старым!",
            ["NewPasswordSameAsOld"] = "❌ Новый пароль не может совпадать со старым!",
            ["Btn_Close"] = "❌ Закрыть",
            // Storekeeper
            ["WarehouseTitle"] = "🏠 Склад: {0}",
            ["Btn_AddProduct"] = "➕ Добавить продукт",
            ["EnterProductName"] = "📝 Введите название продукта:",
            ["SelectUnit"] = "⚖️ Выберите единицу измерения:",
            ["Unit_Kg"] = "Кг",
            ["Unit_Ton"] = "Тонна",
            ["Unit_Meter"] = "Метр",
            ["Unit_Piece"] = "Шт",
            ["Unit_Liter"] = "Литр",
            ["ProductSaved"] = "✅ Продукт сохранен: {0} ({1})",
            ["NotStorekeeper"] = "⛔️ Вы не кладовщик.",
            ["NoWarehouseAssigned"] = "⛔️ Вам не назначен склад."
        },
        ["en"] = new()
        {
            ["Welcome"] = "Welcome! Please select your language:",
            ["LanguageSelected"] = "Language selected: English",
            ["WaitAdmin"] = "Please wait for an admin to assign you a role.",
            ["WelcomeBack"] = "Welcome back, {0}. Type /admin for panel.",
            ["PasswordSet"] = "Password set. You are now the Main Admin. Type /admin to access the panel.",
            ["EnterPassword"] = "System not initialized. Please enter a new Admin Password:",
            ["AccessDenied"] = "You do not have permission to access the Admin Panel.",
            ["NoPending"] = "No pending users found.",
            ["SelectUser"] = "Select a user to manage:",
            ["SelectRole"] = "Select role for User ID {0}:",
            ["RoleUpdated"] = "User role updated to {0}.",
            ["YourRoleUpdated"] = "Your role has been updated to: {0}",
            ["ChangePass"] = "Enter new password:",
            ["PassChanged"] = "Password changed successfully.",
            ["Action_Deputy"] = "Make Deputy",
            ["Action_Storekeeper"] = "Make Storekeeper",
            ["Action_Admin"] = "Make Admin",
            ["Btn_Notifications"] = "Waiting ({0})",
            ["Btn_ChangePass"] = "Change Password",
            ["Btn_AddWarehouse"] = "Add Warehouse",
            ["Btn_WarehouseList"] = "Warehouse List",
            ["Btn_AddCustomer"] = "Add Customer",
            ["Btn_CustomerList"] = "Customer List",
            ["EnterWarehouseName"] = "Enter warehouse name:",
            ["WarehouseAdded"] = "Warehouse added successfully: {0}",
            ["WarehouseDuplicate"] = "❌ A warehouse with this name already exists: {0}",
            ["WarehouseListTitle"] = "📦 Warehouse List:",
            ["EnterCustomerName"] = "Enter customer name:",
            ["CustomerAdded"] = "Customer added successfully: {0}",
            ["CustomerDuplicate"] = "❌ A customer with this name already exists: {0}",
            ["CustomerListTitle"] = "👥 Customer List:",
            ["SelectWarehouse"] = "Select warehouse to assign:",
            ["UserAssignedToWarehouse"] = "User assigned to warehouse {0}.",
            ["NoWarehouses"] = "No warehouses found. Add a warehouse first.",
            ["NoCustomers"] = "No customers found. Add a customer first.",
            ["Menu_Warehouses"] = "📦 Warehouses",
            ["Menu_Customers"] = "👥 Customers",
            ["Btn_Add"] = "Add",
            ["Btn_List"] = "List",
            ["Btn_Back"] = "🔙 Back",
            ["Title_ManageWarehouses"] = "Manage Warehouses:",
            ["Title_ManageCustomers"] = "Manage Customers:",
            ["EnterOldPassword"] = "🔒 Please enter your old password first:",
            ["OldPasswordIncorrect"] = "❌ Old password incorrect!",
            ["NewPasswordSameAsOld"] = "❌ New password cannot be the same as the old one!",
            ["NewPasswordSameAsOld"] = "❌ New password cannot be the same as the old one!",
            ["Btn_Close"] = "❌ Close",
            // Storekeeper
            ["WarehouseTitle"] = "🏠 Warehouse: {0}",
            ["Btn_AddProduct"] = "➕ Add Product",
            ["EnterProductName"] = "📝 Enter product name:",
            ["SelectUnit"] = "⚖️ Select unit of measurement:",
            ["Unit_Kg"] = "Kg",
            ["Unit_Ton"] = "Ton",
            ["Unit_Meter"] = "Meter",
            ["Unit_Piece"] = "Pc",
            ["Unit_Liter"] = "Liter",
            ["ProductSaved"] = "✅ Product saved: {0} ({1})",
            ["NotStorekeeper"] = "⛔️ You are not a storekeeper.",
            ["NoWarehouseAssigned"] = "⛔️ No warehouse assigned to you."
        }
    };

    public string Get(string key, string langCode, params object[] args)
    {
        // Default to 'uz' if not found
        if (string.IsNullOrEmpty(langCode)) langCode = "uz";
        
        if (!_resources.ContainsKey(langCode)) langCode = "uz";

        var dict = _resources[langCode];
        if (dict.TryGetValue(key, out var value))
        {
            return string.Format(value, args);
        }
        return key; // Return key if translation missing
    }
}
